version: '3.8'

services:
  prometheus:
    image: prom/prometheus:v2.51.0
    container_name: loja-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./infra/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - loja-net

  grafana:
    image: grafana/grafana:10.4.0
    container_name: loja-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=135711
    depends_on:
      - prometheus
    networks:
      - loja-net

  rabbitmq:
    image: rabbitmq:3-management
    container_name: loja_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - loja-net

  redis:
    image: redis:7-alpine
    container_name: loja-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --requirepass redis123
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "redis123", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - loja-net

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: loja
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 135711
    ports:
      - "5432:5432"
    volumes:
      - loja-data:/var/lib/postgresql/data
    networks:
      - loja-net

  pedidos-api:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/loja
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 135711
      CATALOGO_URL: http://catalogo-api:8081
      RABBITMQ_HOST: rabbitmq
    depends_on:
      db:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    networks:
      - loja-net

  catalogo-api:
    build: ./catalogo-api
    ports:
      - "8081:8081"
    networks:
      - loja-net

  notificacoes-api:
    build: ./notificacoes-api
    ports:
      - "8083:8083"
    environment:
      RABBITMQ_HOST: rabbitmq
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - loja-net

  gateway:
    build: ./gateway
    ports:
      - "8000:8000"
    depends_on:
      - pedidos-api
      - catalogo-api
    networks:
      - loja-net

volumes:
  loja-data:
  rabbitmq_data:
  redis-data:

networks:
  loja-net:
    driver: bridge